#!/usr/bin/python
import serial
import time
from array import *

z1baudrate = 115200
z1port = '/dev/ttyUSB0'  # set the correct port before running it
data = []

z1serial = serial.Serial(port=z1port, baudrate=z1baudrate)
z1serial.timeout = 2  # set read timeout
# print z1serial  # debug serial.
print(z1serial.is_open)  # True for opened
if z1serial.is_open:
    while True:
        size = z1serial.inWaiting()
        if size:
            singleRead = True
            while True:
                data = z1serial.read(1)
                print(data)
            #print(data[0])
            isinstance(data, int)
    #        for i in range (data):
    #           port[i]
    #           print(len(port))
    #           #print(port[0])
        else:
            print('no data')
        time.sleep(1)
else:
    print('z1serial not open')
# z1serial.close()  # close z1serial if z1serial is open.

while True:
	if data == x00:
		print("start")
		
	else:
		print(":(")
